"""Add selected_locales

Revision ID: 09db5ecca45d
Revises: fe0646eb142a
Create Date: 2020-04-22 21:42:43.475303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09db5ecca45d'
down_revision = 'fe0646eb142a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table('selected_locales',
                    sa.Column('chat_id', sa.BigInteger(), autoincrement=False, nullable=False),
                    sa.Column('locale', sa.String(length=20), nullable=True),
                    sa.PrimaryKeyConstraint('chat_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_table('selected_locales')
    # ### end Alembic commands ###
