"""Initial schema

Revision ID: 37e24ecb8374
Revises: 
Create Date: 2020-04-19 14:12:14.915431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e24ecb8374'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table('entries',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sheet_id', sa.Integer(), nullable=True),
                    sa.Column('position', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('text', sa.Unicode(4096), nullable=True),
                    sa.Column('type', sa.Enum('QUESTION', 'ANSWER', name='entrytype'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Unicode(512), nullable=True),
                    sa.Column('chat_id', sa.BigInteger(), nullable=True),
                    sa.Column('is_started', sa.Boolean(), nullable=True),
                    sa.Column('is_waiting_for_finish', sa.Boolean(), nullable=True),
                    sa.Column('is_finished', sa.Boolean(), nullable=True),
                    sa.Column('rounds', sa.Integer(), nullable=True),
                    sa.Column('is_synchronous', sa.Boolean(), nullable=True),
                    sa.Column('is_showing_result_names', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
                    sa.Column('game_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('game_order', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
                    sa.PrimaryKeyConstraint('game_id', 'user_id')
    )
    op.create_table('sheets',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('game_id', sa.Integer(), nullable=True),
                    sa.Column('hint', sa.Unicode(4096), nullable=True),
                    sa.Column('current_user_id', sa.Integer(), nullable=True),
                    sa.Column('pending_position', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('api_id', sa.Integer(), nullable=True),
                    sa.Column('chat_id', sa.BigInteger(), nullable=True),
                    sa.Column('name', sa.Unicode(512), nullable=True),
                    sa.Column('current_sheet_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['current_sheet_id'], ['sheets.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_entries_sheet_id", 'sheets', ['sheet_id'], ['id'])
        batch_op.create_foreign_key("fk_entries_user_id", 'users', ['user_id'], ['id'])
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_participants_user_id", 'users', ['user_id'], ['id'])
    with op.batch_alter_table('sheets', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_sheets_current_user_id", 'users', ['current_user_id'], ['id'])


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_table('users')
    op.drop_table('sheets')
    op.drop_table('participants')
    op.drop_table('games')
    op.drop_table('entries')
    # ### end Alembic commands ###
