"""Initial schema

Revision ID: 37e24ecb8374
Revises: 
Create Date: 2020-04-19 14:12:14.915431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e24ecb8374'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table('entries',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sheet_id', sa.Integer(), nullable=True),
                    sa.Column('position', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('text', sa.String(), nullable=True),
                    sa.Column('type', sa.Enum('QUESTION', 'ANSWER', name='entrytype'), nullable=True),
                    sa.ForeignKeyConstraint(['sheet_id'], ['sheets.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('chat_id', sa.BigInteger(), nullable=True),
                    sa.Column('is_started', sa.Boolean(), nullable=True),
                    sa.Column('is_waiting_for_finish', sa.Boolean(), nullable=True),
                    sa.Column('is_finished', sa.Boolean(), nullable=True),
                    sa.Column('rounds', sa.Integer(), nullable=True),
                    sa.Column('is_synchronous', sa.Boolean(), nullable=True),
                    sa.Column('is_showing_result_names', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
                    sa.Column('game_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('game_order', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('game_id', 'user_id')
    )
    op.create_table('sheets',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('game_id', sa.Integer(), nullable=True),
                    sa.Column('hint', sa.String(), nullable=True),
                    sa.Column('current_user_id', sa.Integer(), nullable=True),
                    sa.Column('pending_position', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['current_user_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('api_id', sa.Integer(), nullable=True),
                    sa.Column('chat_id', sa.BigInteger(), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('current_sheet_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['current_sheet_id'], ['sheets.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_table('users')
    op.drop_table('sheets')
    op.drop_table('participants')
    op.drop_table('games')
    op.drop_table('entries')
    # ### end Alembic commands ###
