"""Add Entry timestamp

Revision ID: 5b48c4a0a25d
Revises: 37e24ecb8374
Create Date: 2020-04-19 14:15:49.933132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b48c4a0a25d'
down_revision = '37e24ecb8374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('entries', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column('entries', 'timestamp')
    # ### end Alembic commands ###
