"""Add indexes

Revision ID: 6a00ada8daae
Revises: 09db5ecca45d
Create Date: 2020-04-23 20:46:23.604000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a00ada8daae'
down_revision = '09db5ecca45d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.alter_column('position',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.create_index(batch_op.f('ix_entries_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_entries_sheet_id'), ['sheet_id'], unique=False)

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_is_finished'), ['is_finished'], unique=False)

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_game_order'), ['game_order'], unique=False)

    with op.batch_alter_table('sheets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sheets_current_user_id'), ['current_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sheets_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sheets_pending_position'), ['pending_position'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_chat_id'), ['chat_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_chat_id'))

    with op.batch_alter_table('sheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sheets_pending_position'))
        batch_op.drop_index(batch_op.f('ix_sheets_game_id'))
        batch_op.drop_index(batch_op.f('ix_sheets_current_user_id'))

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_game_order'))

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_is_finished'))
        batch_op.drop_index(batch_op.f('ix_games_chat_id'))

    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entries_sheet_id'))
        batch_op.drop_index(batch_op.f('ix_entries_position'))
        batch_op.alter_column('position',
                              existing_type=sa.INTEGER(),
                              nullable=True)

    # ### end Alembic commands ###
