"""Add Entry message_id

Revision ID: af05c8354ff6
Revises: a1c3be680840
Create Date: 2020-05-07 21:22:05.825923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af05c8354ff6'
down_revision = 'a1c3be680840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('message_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_chat_message_id', ['chat_id', 'message_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_index('idx_chat_message_id')
        batch_op.drop_column('message_id')
        batch_op.drop_column('chat_id')

    # ### end Alembic commands ###
