"""detailed Telegram user name

Revision ID: b5a049c7a6fd
Revises: ecb9ccd924ac
Create Date: 2020-06-28 13:45:46.588892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column, Unicode, case, func

# revision identifiers, used by Alembic.
revision = 'b5a049c7a6fd'
down_revision = 'ecb9ccd924ac'
branch_labels = None
depends_on = None

# Table declaration of the intermediate state to do the data transformation with SQLAlchemy
users = table('users',
    column('name', Unicode),
    column('first_name', Unicode),
    column('last_name', Unicode),
    column('username', Unicode)
)


def upgrade():
    # ### commands auto generated by Alembic ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.Unicode(length=512), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.Unicode(length=512), nullable=True))
        batch_op.add_column(sa.Column('username', sa.Unicode(length=512), nullable=True))

    op.execute(
        users.update()
        .values({
            'first_name': users.c.name,
            'username': case([(users.c.name.like("@%"), func.substr(users.c.name, 2, 512))]),
        }))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.alter_column('first_name',
                              existing_type=sa.VARCHAR(length=512),
                              nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=512), nullable=True))

    op.execute(
        users.update()
        .values({
            'name': case([(users.c.username != None, func.concat('@', users.c.username))], else_=users.c.first_name),
        }))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('username')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(length=512),
                              nullable=False)

    # ### end Alembic commands ###
