"""Add timestamps to Game

Revision ID: ecb9ccd924ac
Revises: af05c8354ff6
Create Date: 2020-05-10 17:53:13.114662

"""
import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import table, column, DateTime, Boolean, case

revision = 'ecb9ccd924ac'
down_revision = 'af05c8354ff6'
branch_labels = None
depends_on = None

# Table declaration of the intermediate state to do the data transformation with SQLAlchemy
games = table('games',
    column('started', DateTime),
    column('finished', DateTime),
    column('is_started', Boolean),
    column('is_finished', Boolean)
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finished', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('started', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_games_finished'), ['finished'], unique=False)

    # op.execute('UPDATE games SET'
    #            '  finished = CASE WHEN is_finished THEN NOW() END,'
    #            '  started = CASE WHEN is_started THEN NOW() END')
    op.execute(
        games.update()
        .values({
            'started': case([(games.c.is_started, datetime.datetime.now(datetime.timezone.utc))]),
            'finished': case([(games.c.is_finished, datetime.datetime.now(datetime.timezone.utc))]),
        }))

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index('ix_games_is_finished')
        batch_op.drop_column('is_finished')
        batch_op.drop_column('is_started')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_started', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('is_finished', sa.BOOLEAN(), nullable=False))
        batch_op.create_index('ix_games_is_finished', ['is_finished'], unique=False)

    op.execute('UPDATE games SET'
               '  is_finished = finished IS NOT NULL,'
               '  is_started = started IS NOT NULL')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_finished'))
        batch_op.drop_column('started')
        batch_op.drop_column('finished')

    # ### end Alembic commands ###
