"""Add NOT NULL constraints

Revision ID: fe0646eb142a
Revises: 5b48c4a0a25d
Create Date: 2020-04-19 21:30:15.357105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0646eb142a'
down_revision = '5b48c4a0a25d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.alter_column('entries', 'sheet_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('entries', 'text',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('entries', 'timestamp',
                    existing_type=sa.DATETIME(),
                    nullable=False)
    op.alter_column('entries', 'type',
                    existing_type=sa.VARCHAR(length=8),
                    nullable=False)
    op.alter_column('entries', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('games', 'chat_id',
                    existing_type=sa.BIGINT(),
                    nullable=False)
    op.alter_column('games', 'is_finished',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('games', 'is_showing_result_names',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('games', 'is_started',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('games', 'is_synchronous',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('games', 'is_waiting_for_finish',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('games', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('sheets', 'game_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('users', 'api_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('users', 'chat_id',
                    existing_type=sa.BIGINT(),
                    nullable=False)
    op.alter_column('users', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.alter_column('users', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('users', 'chat_id',
                    existing_type=sa.BIGINT(),
                    nullable=True)
    op.alter_column('users', 'api_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('sheets', 'game_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('games', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('games', 'is_waiting_for_finish',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('games', 'is_synchronous',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('games', 'is_started',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('games', 'is_showing_result_names',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('games', 'is_finished',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('games', 'chat_id',
                    existing_type=sa.BIGINT(),
                    nullable=True)
    op.alter_column('entries', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('entries', 'type',
                    existing_type=sa.VARCHAR(length=8),
                    nullable=True)
    op.alter_column('entries', 'timestamp',
                    existing_type=sa.DATETIME(),
                    nullable=True)
    op.alter_column('entries', 'text',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('entries', 'sheet_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
